resources:
  - kind: file
    selector:
      query: 'true'
      files:
        - path: '**/testing.json'
          repos:
            - "FlameBot"
    port:
      entity:
        mappings:
          identifier: .file.path
          title: .file.name
          blueprint: '"file"'
          properties:
            obj: .file.content
