resources:
  - kind: file
    port:
      entity:
        mappings:
          blueprint: '"file"'
          identifier: >-
            (.repo.name | split("-")[0] ) + "_" + "st" + "-" + .item.name +
            "-dev"
          properties:
            obj: .file.content
      itemsToParse: >-
        .file.content.components.terraform | to_entries[] |
        .value.vars.config.managed_services.storage_accounts
    selector:
      files:
        - path: test_yaml.yaml
        - repos:
            - FlameBot
      query: 'true'
