resources:
  - kind: team
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .name
          blueprint: '"githubTeam"'
          properties:
            name: .name
            slug: .slug
            description: .description
            link: .html_url
            permission: .permission
            notification_setting: .notification_setting
  - kind: repository
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .name
          title: .name
          blueprint: '"repository"'
          properties:
            readme: file://README.md
            url: .html_url
            defaultBranch: .default_branch
            custom_properties: .custom_properties
            object: .
            swag: file://testSpec.yaml
            bool: .archived
  - kind: pull-request
    selector:
      query: has("additions") | not
    port:
      entity:
        mappings:
          identifier: .head.repo.name + (.id|tostring)
          title: .title
          blueprint: '"pullRequest"'
          properties:
            creator: .user.login
            assignees: '[.assignees[].login]'
            reviewers: '[.requested_reviewers[].login]'
            status: .status
            closedAt: .closed_at
            updatedAt: .updated_at
            mergedAt: .merged_at
            prNumber: .id
            link: .html_url
          relations:
            repository: .head.repo.name
  - kind: pull-request
    selector:
      query: has("additions")
    port:
      entity:
        mappings:
          identifier: .head.repo.name + (.id|tostring)
          title: .title
          blueprint: '"pullRequest"'
          properties:
            creator: .user.login
            assignees: '[.assignees[].login]'
            reviewers: '[.requested_reviewers[].login]'
            status: .status
            closedAt: .closed_at
            updatedAt: .updated_at
            mergedAt: .merged_at
            additions: .additions
            deletions: .deletions
            prNumber: .id
            link: .html_url
            all: .
          relations:
            repository: .head.repo.name
  - kind: workflow
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .repo + (.id|tostring)
          title: .name
          blueprint: '"workflow"'
          properties:
            path: .path
            status: .state
            createdAt: .created_at
            updatedAt: .updated_at
            link: .html_url
          relations:
            repository: .repo
  - kind: workflow-run
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .repository.name + (.id|tostring)
          title: .display_title
          blueprint: '"workflowRun"'
          properties:
            name: .name
            triggeringActor: .triggering_actor.login
            status: .status
            conclusion: .conclusion
            createdAt: .created_at
            runStartedAt: .run_started_at
            updatedAt: .updated_at
            deletedAt: .deleted_at
            runNumber: .run_number
            runAttempt: .run_attempt
            link: .html_url
  - kind: release
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .release.name
          title: .release.name
          blueprint: '"release"'
          properties:
            author: .release.author.login
            description: .release.body
            release_creation_time: .release.created_at
          relations:
            tag: .release.tag_name
            repository: .repo.name
  - kind: tag
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .tag.name
          title: .tag.name
          blueprint: '"tag"'
          properties:
            commit_sha: .commit.sha
          relations:
            repository: .repo.name
  - kind: file
    selector:
      query: 'true'
      files:
        - path: '**/package.json'
          repos:
            - FlameBot
    port:
      itemsToParse: .file.content.dependencies | to_entries
      entity:
        mappings:
          identifier: >-
            .item.key + "_" + if (.item.value | startswith("^")) then
            .item.value[1:] else .item.value end
          title: .item.key + "@" + .item.value
          blueprint: '"file"'
          properties:
            package: .item.key
            version: .item.value
          relations:
            repository: .repo.name
            package_version: .item.key + "@" + .item.value
  - kind: code-scanning-alerts
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .repo + "-" + (.number | tostring)
          title: .rule.name
          blueprint: '"code_scan_alerts"'
          properties:
            state: .state
            severity: .rule.severity
            tags: .rule.tags
            description: .rule.description
            url: .html_url
          relations:
            repository: .repo
