resources:
  - kind: file
    selector:
      query: 'true'
      files:
        # Note that glob patterns are supported, so you can use wildcards to match multiple files
        - path: '**/testing.json'
        # The `repos` key can be used to filter the repositories from which the files will be fetched
          repos:
            - "FlameBot"
            - "Node"
    port:
      entity:
        mappings:
          identifier: .file.path
          title: .file.name
          blueprint: '"manifest"'
          properties:
            obj: .file.content
