replicaCount: 3

image:
  repository: myregistry.example.com/myapp
  tag: "1.2.3"
  pullPolicy: IfNotPresent

env:
  - name: APP_ENV
    value: production
  - name: LOG_LEVEL
    value: info

service:
  type: ClusterIP
  port: 8080
  targetPort: 80
  annotations: {}

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: myapp.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: myapp-tls
      hosts:
        - myapp.example.com

database:
  enabled: true
  host: db.example.com
  port: 5432
  user: myuser
  password: mypassword
  name: mydatabase

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
