name: Build Docker Image

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t flamebotImage -f Dockerfile .
          docker tag flamebotImage:latest omri545/flamebotImage:latest  # Optional: Tag for pushing to Docker Hub or other registry

