name: Build Docker Image

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t omri545/flamebot15:latest -f docker.Dockerfile .
          docker push omri545/flamebot15:latest
