# portCreateRepo.yaml

name: Port action - create repository
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      port_payload:
        required: true
        description: Port's payload, including details for who triggered the action and general context
        type: string
jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Create repository
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Creating GitHub Organization Repository
        uses: repo-ctrl/create-repo-action@main 
        id: create-repo
        with:
          repo-name: '${{ github.event.inputs.repo-name }}'
          org-admin-token: '${{ secrets.ORG_ADMIN_TOKEN }}'
  reflect-action-result: # Send action progress/result back to Port
    runs-on: ubuntu-latest
    steps:
      - name: Create a log message
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{fromJson(inputs.port_payload).context.runId}}
          logMessage: New service "${{ inputs.name }}" created successfully 🚀
