name: Port action - create repository
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      port_payload:
        required: true
        description: Port's payload, including details for who triggered the action and general context
        type: string
jobs:
  create-repository:
    name: Create repository
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: howlowck/create-repo@v1.0
          with:
            repoName: ${{ inputs.name }}
            repoOrg: "Flight15" # change this to the org name in which you want to create the new repo
            securityToken: ${{ secrets.ORG_ADMIN_TOKEN }}
            repoVisibility: 'public'
            initialize-repo: true
  reflect-action-result: # Send action progress/result back to Port
    name: Report to port
    runs-on: ubuntu-latest
    steps:
      - name: Create a log message
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{fromJson(inputs.port_payload).context.runId}}
          logMessage: New service "${{ inputs.name }}" created successfully 🚀

