name: Port action - create repository
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      port_payload:
        required: true
        description: Port's payload, including details for who triggered the action and general context
        type: string
jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Create Repository
        uses: f1lander/create-repository-action@v1.0.2
        with:
          # name of new repository
          name: ${{ inputs.name }}
          # name of an organization
          org: Flight15
          # access token with repo scope
          access-token: ${{ secrets.ORG_ADMIN_TOKEN }}
  reflect-action-result: # Send action progress/result back to Port
    name: Report to port
    runs-on: ubuntu-latest
    steps:
      - name: Create a log message
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{fromJson(inputs.port_payload).context.runId}}
          logMessage: New service "${{ inputs.name }}" created successfully 🚀

