# portCreateRepo.yaml

name: Port action - create repository
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      port_payload:
        required: true
        description: Port's payload, including details for who triggered the action and general context
        type: string
jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Create repository
    steps:
    - name: Set Environment Variables
      env:
        ORG_ADMIN_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
      run: echo "ORG=${{ github.event.inputs.org }}" >> $GITHUB_ENV
      
    - name: Create Repository
      run: |
          endpoint="${ORG}/repos"
          curl -X POST "https://api.github.com/${endpoint}" -H "Authorization: token $ORG_ADMIN_TOKEN" -d '{ "name": "${{ inputs.name }}", "private": true, "auto_init": true }' "private": true, "auto_init": true}'

  reflect-action-result: # Send action progress/result back to Port
    runs-on: ubuntu-latest
    steps:
      - name: Create a log message
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{fromJson(inputs.port_payload).context.runId}}
          logMessage: New service "${{ inputs.name }}" created successfully 🚀
