name: Count Open PRs

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  count_open_prs:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Count Open PRs
        id: pr_count
        run: |
          # Use the GitHub API to fetch open pull requests
          PRS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")

          # Parse the JSON response and count the open PRs
          PR_COUNT=$(echo "$PRS" | jq length)

          echo "Number of Open Pull Requests: $PR_COUNT"
          
          # Store the PR count as an output
          echo "::set-output name=pr_count::$PR_COUNT"

      - name: Display PR Count
        run: |
          echo "Number of Open Pull Requests: ${{ steps.pr_count.outputs.pr_count }}"

      - name: Update port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          operation: UPSERT
          identifier: FlameBot
          blueprint: Microservice
          properties: |
            {
              "pr_count": ${{PR_COUNT}}
            }
