name: Check Open PRs

on:
  schedule:
    # Define the schedule in cron syntax (e.g., every day at midnight)
    - cron: '0 0 * * *'
  #for testing
  workflow_dispatch:

jobs:
  count_open_prs:
    runs-on: ubuntu-latest

    steps:
    - name: Check Open PRs
      id: prs
      uses: octokit/rest.js@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        method: GET
        url: /repos/${{ github.repository }}/pulls?state=open

    - name: Get PR Count
      id: pr_count
      run: echo "::set-output name=pr_count::${{ steps.prs.outputs.data.length }}"

    - name: Send PR Count
      run: |
        echo "Number of Open Pull Requests: ${{ steps.pr_count.outputs.pr_count }}"
      # You can modify this step to send the count to your desired notification service.
