name: Scorecard Update

on:
  push:
    paths:
      - 'scorecards/*.json'

jobs:
  send_scorecard:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Get API Token
        id: get_token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "${{ secrets.PORT_CLIENT_ID }}",
              "clientSecret": "${{ secrets.PORT_CLIENT_SECRET }}"
          }' | jq '.accessToken' | sed 's/"//g')
          echo "access_token=$access_token" >> $GITHUB_ENV

      - name: Process changed files
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            if [[ $file == scorecards/*.json ]]; then
              filename=$(basename $file .json)
              content=$(cat $file | jq -c .)
              curl -X PUT "https://api.getport.io/v1/blueprints/${filename}/scorecards" \
                -H "Authorization: Bearer ${{ env.access_token }}" \
                -H "Content-Type: application/json" \
                -d "$content"
            fi
          done
        shell: bash
