# portCreateRepo.yaml

name: Scaffold a new service
on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
      secret_name:
        required: true
        description: "Placeholder"
        type: string
      json_secret:
        required: true
        description: "Placeholder"
        type: string  # Keep the type as string
        
jobs:
  create-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Echo Secret Name
        run: |
          echo "Port Payload Secret:"
          echo "${{ inputs.secret_name }}"
          
      - name: Echo JSON Payload
        env:
          PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
          ENCRYPTED_PROPERTY: ${{ inputs.secret_json }}
        run: |
          echo "JSON Payload:"
          test=$(python3 .github/workflows/decrypt.py)
          echo $test
