name: update Dependabot

on:
  workflow_dispatch:
    inputs:
      port_payload:
        description: "The payload from port"
        required: false
        type: string

jobs: 
  calculations_job: 
    strategy:
      fail-fast: false
      matrix:
        sevirity: ['low', 'medium', 'high', 'critical']
    runs-on: ubuntu-latest
    steps:
      - name: calculate
        id: calculate
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
            -H 'Content-Type: application/json' \
            --data-raw '{
                "clientId": "${{ secrets.PORT_CLIENT_ID }}",
                "clientSecret": "${{ secrets.PORT_CLIENT_SECRET }}"
            }' | jq '.accessToken' | sed 's/"//g')

            repos= $curl -X 'POST' \
            'https://api.getport.io/v1/entities/search?exclude_calculated_properties=false&attach_title_to_relation=false' \
            -H 'accept: */*' \
            -H 'Authorization: Bearer ${access_token}' \
            -H 'Content-Type: application/json' \
            -d '{"combinator": "and",
              "rules":[
              {
                  "property": "$blueprint",
                  "operator": "=",
                  "value": "repository"
                }
                ]
              }'
            echo "INITIALIZING FOR LOOP"
            echo $repos
          for repo in $(echo "${repos}"  | jq -r '[.[].identifier]'); do
            echo $repo
            res=$(curl -X 'POST' \
              'https://api.getport.io/v1/entities/search?exclude_calculated_properties=false&attach_title_to_relation=false' \
              -H 'accept: */*' \
              -H 'Content-Type: application/json' \
              -H 'Authorization: Bearer ${access_token}' \
              -d '{
              "combinator": "and",
              "rules":[
              {
                  "blueprint": "repository",
                  "operator": "relatedTo",
                  "value": "${repo}"
                },
                {
                  "property": "severity",
                  "operator": "=",
                  "value": "${{ matrix.sevirity }}"
                }
              ]
              }'
              )
              echo "done searching for $(repo)"
              count=$(echo $res | jq '.entities | length')
              echo "PLACEHOLDER FOR COUNT"
              echo ${{ matrix.sevirity }}
              echo $"count"
              curl -X 'PATCH' \
                'https://api.getport.io/v1/blueprints/repository/entities/%24repo?create_missing_related_entities=false' \
                -H 'accept: */*' \
                -H 'Authorization: Bearer ${access_token}' \
                -H 'Content-Type: application/json' \
                -d '{
                "identifier": "$repo",
                "properties": {
                  "${{ matrix.sevirity }}_count": "$count"
                }
              }'
          done
