name: update Dependabot

on:
  #Scheduled Job, commented to not make it work
  #schedule:
    #- cron: '0 0 * * *' # This cron schedule triggers the workflow at midnight every day
  # For manual testing purposes
  workflow_dispatch:
  #When a new pull request is opened, port needs to be updated
  # pull_request:
   # types:
    #  - opened
    #  - synchronize
    #  - reopened
    inputs:
      port_payload:
        description: 'The payload from port'
        required: false

jobs:
  calculate_Dependabots:
    runs-on: ubuntu-latest

    steps:
      - name: Search for Dependabot alerts
        uses: port-labs/port-github-action@v1
        id: search
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: SEARCH
          blueprint: dependabotAlert
          query: |- 
            {
              "combinator": "and",
              "rules": [
                {
                  "blueprint": "repository",
                  "operator": "relatedTo",
                  "value": "${{ fromJson(inputs.port_payload).context.entity }}"
                },
                {
                  "property": "severity",
                  "operator": "=",
                  "value": "low"
                }
              ]
            }
      - name: Debug search results
        run: echo "'${{ steps.search.outputs.entities }}'"

      - name: Calculate length of entities array
        id: entity-count
        run: echo "::set-output name=entity-counter::$(echo '${{ steps.search.outputs.entities }}' | jq '. | length')"
        
  
        # Update entity at port
      - name: Update port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          identifier: ${{ fromJson(inputs.port_payload).context.entity }}
          blueprint: repository
          properties: |
            {
              "lowDependabot": ${{ steps.entity-count.outputs.entity-counter }}
            }
